//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        [ScaffoldColumn(false)]
        public int idvideo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = " El título es requerido"), MaxLength(100)]
        [Display(Name = "Título del Video")]
        public string titulo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de Publicacion")]
        public System.DateTime fecha_publi { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = " El formato es requerido"), MaxLength(55)]
        [Display(Name = "Formato")]
        public string formato { get; set; }
        [DataType(DataType.Duration)]
        [Range(1, 9999, ErrorMessage = "La duración debe ser un número")]
        [Required(ErrorMessage = "La duración es requerida")]
        [Display(Name = "Duración (Minutos)")]
        public int duracion { get; set; }
        [Display(Name = "Categoría")]
        public int categoria { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
    }
}

